// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCby4NWOOrCQbwpBmbgqtFasJM5kusD4ig',
    appId: '1:978066257302:web:5f60cf1863758cb7e159b7',
    messagingSenderId: '978066257302',
    projectId: 'piensa-play-56a1c',
    authDomain: 'piensa-play-56a1c.firebaseapp.com',
    storageBucket: 'piensa-play-56a1c.firebasestorage.app',
    measurementId: 'G-G60RPSQLE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkIlAlkbuuLHU_qKyDpz-RQFcgzd9v_NM',
    appId: '1:978066257302:android:6554174bb6aae089e159b7',
    messagingSenderId: '978066257302',
    projectId: 'piensa-play-56a1c',
    storageBucket: 'piensa-play-56a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19vR8IkViuorKVHjRxLVCytx2OfqMlxY',
    appId: '1:978066257302:ios:00f0b5c31a5a5f17e159b7',
    messagingSenderId: '978066257302',
    projectId: 'piensa-play-56a1c',
    storageBucket: 'piensa-play-56a1c.firebasestorage.app',
    iosBundleId: 'com.example.piensaPlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19vR8IkViuorKVHjRxLVCytx2OfqMlxY',
    appId: '1:978066257302:ios:00f0b5c31a5a5f17e159b7',
    messagingSenderId: '978066257302',
    projectId: 'piensa-play-56a1c',
    storageBucket: 'piensa-play-56a1c.firebasestorage.app',
    iosBundleId: 'com.example.piensaPlay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCby4NWOOrCQbwpBmbgqtFasJM5kusD4ig',
    appId: '1:978066257302:web:052ed64bdcec030fe159b7',
    messagingSenderId: '978066257302',
    projectId: 'piensa-play-56a1c',
    authDomain: 'piensa-play-56a1c.firebaseapp.com',
    storageBucket: 'piensa-play-56a1c.firebasestorage.app',
    measurementId: 'G-XPSVY3M0EW',
  );
}
